-- 021_category_nesting.sql
-- Nesting categories in the closet (ADR-0113).
--
-- NOT REQUIRED. Nothing waits on this file. Nesting shipped with NO schema change.
--
-- The parent of a category is stored in `client_categories.group_label`, which
-- migration 006 created in June as "display-only section header
-- (Clothing/Accessories/...)" and which nothing has ever read or written. That is
-- the same question a parent answers: which group does this category sit in. It is
-- nullable and unused, so reusing it needed no DDL, which is what let this ship on
-- the day the database password turned out to be unavailable.
--
-- Two places translate `group_label` to the name the code uses, `parent_slug`, and
-- nowhere else knows:
--   atelier-builder  src/hooks/useClientCategories.ts
--   atelier-looks    src/lib/queries.ts  (getClientCategories)
--
-- IF A PROPERLY NAMED COLUMN IS EVER WANTED, this is the whole change: add it,
-- copy the values across, then point those two files at it. Additive and nullable,
-- so it is safe to apply at any time, and safe never to apply. Do NOT drop
-- group_label afterwards -- a rollback would need it, and dropping is against the
-- shared-database rule (ADR-0006) regardless.

-- ALTER TABLE client_categories ADD COLUMN IF NOT EXISTS parent_slug text;
-- UPDATE client_categories SET parent_slug = group_label WHERE parent_slug IS NULL;
-- CREATE INDEX IF NOT EXISTS idx_client_categories_client
--   ON client_categories(client_id, sort_order);
-- ALTER TABLE client_categories DROP CONSTRAINT IF EXISTS client_categories_no_self_parent;
-- ALTER TABLE client_categories ADD CONSTRAINT client_categories_no_self_parent
--   CHECK (parent_slug IS NULL OR parent_slug <> slug);
-- NOTIFY pgrst, 'reload schema';

-- A category cannot be its own parent. Enforced in the application instead
-- (`wouldCycle` in src/lib/categoryNesting.ts refuses it before it can be saved, and
-- `parentMapFrom` drops it on read if one ever gets in), because the constraint above
-- needs DDL and the application has to be cycle-safe either way: the tree is typed by
-- a stylist through a dropdown, and a two-hop cycle is two presses away.
